// Apple splash screen links for PWA
// Generated by pwa-asset-generator

const appleSplashScreens = [
  { width: 1024, height: 1366, ratio: 2, portrait: "apple-splash-2048-2732.png", landscape: "apple-splash-2732-2048.png" },
  { width: 834, height: 1194, ratio: 2, portrait: "apple-splash-1668-2388.png", landscape: "apple-splash-2388-1668.png" },
  { width: 768, height: 1024, ratio: 2, portrait: "apple-splash-1536-2048.png", landscape: "apple-splash-2048-1536.png" },
  { width: 820, height: 1180, ratio: 2, portrait: "apple-splash-1640-2360.png", landscape: "apple-splash-2360-1640.png" },
  { width: 834, height: 1112, ratio: 2, portrait: "apple-splash-1668-2224.png", landscape: "apple-splash-2224-1668.png" },
  { width: 810, height: 1080, ratio: 2, portrait: "apple-splash-1620-2160.png", landscape: "apple-splash-2160-1620.png" },
  { width: 744, height: 1133, ratio: 2, portrait: "apple-splash-1488-2266.png", landscape: "apple-splash-2266-1488.png" },
  { width: 440, height: 956, ratio: 3, portrait: "apple-splash-1320-2868.png", landscape: "apple-splash-2868-1320.png" },
  { width: 402, height: 874, ratio: 3, portrait: "apple-splash-1206-2622.png", landscape: "apple-splash-2622-1206.png" },
  { width: 420, height: 912, ratio: 3, portrait: "apple-splash-1260-2736.png", landscape: "apple-splash-2736-1260.png" },
  { width: 430, height: 932, ratio: 3, portrait: "apple-splash-1290-2796.png", landscape: "apple-splash-2796-1290.png" },
  { width: 393, height: 852, ratio: 3, portrait: "apple-splash-1179-2556.png", landscape: "apple-splash-2556-1179.png" },
  { width: 390, height: 844, ratio: 3, portrait: "apple-splash-1170-2532.png", landscape: "apple-splash-2532-1170.png" },
  { width: 428, height: 926, ratio: 3, portrait: "apple-splash-1284-2778.png", landscape: "apple-splash-2778-1284.png" },
  { width: 375, height: 812, ratio: 3, portrait: "apple-splash-1125-2436.png", landscape: "apple-splash-2436-1125.png" },
  { width: 414, height: 896, ratio: 3, portrait: "apple-splash-1242-2688.png", landscape: "apple-splash-2688-1242.png" },
  { width: 414, height: 896, ratio: 2, portrait: "apple-splash-828-1792.png", landscape: "apple-splash-1792-828.png" },
  { width: 414, height: 736, ratio: 3, portrait: "apple-splash-1242-2208.png", landscape: "apple-splash-2208-1242.png" },
  { width: 375, height: 667, ratio: 2, portrait: "apple-splash-750-1334.png", landscape: "apple-splash-1334-750.png" },
  { width: 320, height: 568, ratio: 2, portrait: "apple-splash-640-1136.png", landscape: "apple-splash-1136-640.png" },
]

export function AppleSplashLinks() {
  return (
    <>
      {appleSplashScreens.map((screen) => (
        <link
          key={`portrait-${screen.width}-${screen.height}-${screen.ratio}`}
          rel="apple-touch-startup-image"
          href={`/icons/${screen.portrait}`}
          media={`(device-width: ${screen.width}px) and (device-height: ${screen.height}px) and (-webkit-device-pixel-ratio: ${screen.ratio}) and (orientation: portrait)`}
        />
      ))}
      {appleSplashScreens.map((screen) => (
        <link
          key={`landscape-${screen.width}-${screen.height}-${screen.ratio}`}
          rel="apple-touch-startup-image"
          href={`/icons/${screen.landscape}`}
          media={`(device-width: ${screen.width}px) and (device-height: ${screen.height}px) and (-webkit-device-pixel-ratio: ${screen.ratio}) and (orientation: landscape)`}
        />
      ))}
    </>
  )
}

